# Python EDA Full Course- Data Sense - Libraries:- 2. Numpy

# 1. Introduction

**Overview of Numpy**

Numpy (Numerica Python) is a core library in Python for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Numpy is the foundation upon which many other data science and machine learning libraries, such as Pandas, SciPy, and TensorFlow, are built.

**Why is it used?**

Numpy is used because it allows you to perform efficient operations on large datasets. Compared to Python lists, Numpy arrays (ndarrays) consume less memory and provide better performance for mathematical operations. This efficiency is crucial when dealing with large-scale data in fields like data science, machine learning, and scientific computing.

**When to use Numpy?**

Use Numpy when you need to handle numerical data and perform mathematical operations on it. It's particularly useful for:

**1. Array Manipulation:** Numpy provides a versatile set of tools to create, reshape, and manipulate arrays.

**2. Mathematical Computations:** It offers a wide range of mathematical functions, including statistical, algebraic, and trigonometric functions.

**3. Performance:** Numpy is optimized for performance, making it suitable for operations on large datasets.

# 2. What This Library Does

**1. N-dimensional Arrays (ndarray)**

**Explanation:**

Numpy's core data structure is the ndarray, which stands for "N-dimensional array". An ndarray is a generalization of a matrix, and it can have any number of dimensions (hence the name "N-dimensional").

**Why use Numpy arrays instead of Python lists?**

Homogeneous Data: Numpy arrays are designed to handle homogeneous data (i.e., data of the same type). This allows for more efficient storage and processing compared to Python lists, which can hold mixed data types.
Vectorized Operations: Numpy arrays support vectorized operations, meaning that operations applied to the array are automatically applied element-wise. This eliminates the need for explicit loops and makes the code more concise and efficient.
Broadcasting: Numpy allows operations on arrays of different shapes and sizes without requiring explicit copying or resizing. This is known as broadcasting, and it simplifies many types of calculations.

**Example 1: Creating a Numpy array**

In [7]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)


[1 2 3 4 5]


**Explanation:**
  
This code creates a one-dimensional Numpy array with the values [1, 2, 3, 4, 5]. A Numpy array is similar to a Python list, but it is much more powerful in terms of mathematical and numerical operations.

**Example 2: Creating a 2D Numpy array (matrix)**

In [12]:
# Creating a 2D Numpy array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[[1 2 3]
 [4 5 6]]


**Explanation:** Here, we create a two-dimensional array, often referred to as a matrix. This matrix has 2 rows and 3 columns. Unlike Python lists, Numpy arrays can efficiently handle multi-dimensional data structures like matrices and tensors.


**2. Mathematical Operations**

Numpy is built to perform fast, efficient mathematical operations on arrays. These operations can be as simple as element-wise addition or as complex as matrix multiplication.

**Why are mathematical operations with Numpy important?**

**Efficiency:** Numpy's mathematical functions are implemented in C, making them much faster than equivalent operations in pure Python.

**Simplicity:** Numpy's vectorized operations allow you to apply mathematical functions to entire arrays without needing to write explicit loops.

**Functionality:** Numpy includes a wide range of mathematical functions, including basic arithmetic, linear algebra, trigonometry, and more, making it a powerful tool for numerical analysis.

**Example 1: Element-wise operations**

In [16]:
# Creating an array and performing element-wise operations
array = np.array([1, 2, 3, 4])
array = array + 10
print(array)


[11 12 13 14]


**Explanation:** This example creates an array [1, 2, 3, 4] and adds 10 to each element. Numpy automatically applies the operation to each element, leveraging broadcasting. Broadcasting allows operations to be applied across arrays of different shapes, which simplifies the code and improves efficiency.


**Example 2: Matrix multiplication**



In [20]:
# Creating two matrices and performing matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
result = np.dot(matrix_a, matrix_b)
print(result)


[[19 22]
 [43 50]]


**Explanation:** Matrix multiplication is a fundamental operation in linear algebra. In this example, np.dot() performs matrix multiplication between matrix_a and matrix_b. The operation multiplies corresponding elements from rows and columns and sums them up to produce the resulting matrix.

**3. Array Reshaping**

Numpy allows you to change the shape of an array without modifying its data. Reshaping is a powerful feature that is particularly useful when preparing data for machine learning algorithms or when manipulating data in different dimensions.

**Why reshape arrays?**
    
**Data Preparation:** Many machine learning algorithms require input data to be in a specific shape, such as a matrix or tensor. Reshaping allows you to convert your data into the necessary format without altering the data itself.

**Flexibility:** Reshaping allows you to switch between different views of your data, making it easier to apply different operations and analyses.

**Example 1: Reshaping an array**

In [24]:
# Creating a 1D array and reshaping it into a 2D array
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((2, 3))
print(reshaped_array)


[[1 2 3]
 [4 5 6]]


**Explanation:** In this example, a 1D array with 6 elements is reshaped into a 2D array with 2 rows and 3 columns. The total number of elements must remain the same after reshaping. This operation is useful for converting flat data into a more structured form.

**Example 2: Flattening an array**

In [27]:
# Flattening a 2D array into a 1D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
flat_array = matrix.flatten()
print(flat_array)


[1 2 3 4 5 6]


**Explanation:** The flatten() method converts a multi-dimensional array into a one-dimensional array. This is the reverse of reshaping, and it's often used when you need to reduce the dimensionality of your data for certain types of analysis or when passing data to functions that require a flat input.


**4. Advanced Array Operations**
    
**Array Slicing and Indexing**
    
**Explanation:** Slicing and indexing allow you to access and modify specific elements or subsets of an array. This is similar to how you slice lists in Python, but with more powerful capabilities.

**Example 1: Basic Slicing**

In [32]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
slice_1 = array[1:4]  # Access elements from index 1 to 3
print(slice_1)


[20 30 40]


**Explanation:** This example demonstrates how to slice an array to access a subset of its elements. The slice [1:4] returns elements from index 1 to 3 (20, 30, 40).

**Example 2: Slicing a 2D Array**

In [35]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_2 = matrix[:2, 1:3]  # Access a submatrix
print(slice_2)


[[2 3]
 [5 6]]


**Explanation:** Slicing can also be applied to multi-dimensional arrays. Here, matrix[:2, 1:3] extracts a 2x2 submatrix.

**Boolean Indexing**

**Explanation:** Boolean indexing allows you to filter elements of an array based on conditions.
    
**Example: Filtering with Boolean Indexing**

In [38]:
array = np.array([10, 20, 30, 40, 50])
filtered_array = array[array > 25]  # Filter elements greater than 25
print(filtered_array)


[30 40 50]


**Explanation:** This example shows how to use a boolean condition to filter an array. The resulting array contains only elements greater than 25.

**5. Mathematical Functions**

**A.Aggregation Functions**

**Explanation:** Aggregation functions compute a summary statistic (e.g., sum, mean, max) across the elements of an array.

**Example 1: Sum and Mean**

In [41]:
array = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(array)
average = np.mean(array)
print("Sum:", total_sum)
print("Mean:", average)


Sum: 15
Mean: 3.0


**Explanation:** np.sum() computes the sum of all elements, while np.mean() calculates the average. These are common operations when analyzing data.

**Example 2: Maximum and Minimum**

In [44]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
max_value = np.max(matrix)
min_value = np.min(matrix)
print("Max:", max_value)
print("Min:", min_value)


Max: 9
Min: 1


**Explanation:** np.max() and np.min() return the maximum and minimum values in the array, respectively. These functions are useful for finding the range of data.

**6. Linear Algebra Operations**

**Dot Product**

**Explanation:** The dot product is a key operation in linear algebra, used in many applications including machine learning algorithms.

**Example: Dot Product of Vectors**

In [47]:
vector_a = np.array([1, 2])
vector_b = np.array([3, 4])
dot_product = np.dot(vector_a, vector_b)
print(dot_product)


11


**Explanation:** The dot product of two vectors is calculated by multiplying corresponding elements and summing the results. In this example, the dot product is 1*3 + 2*4 = 11.

**Matrix Multiplication**

**Explanation:** Matrix multiplication is a fundamental operation for many linear algebra applications.

**Example: Matrix Multiplication**

In [50]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
product = np.dot(matrix_a, matrix_b)
print(product)


[[19 22]
 [43 50]]


**Explanation:** This example demonstrates matrix multiplication, a critical operation in fields like machine learning, computer graphics, and data science.

**7. Random Number Generation**

**Generating Random Numbers**

**Explanation:** Numpy provides tools to generate random numbers, which is essential for simulations, initializing algorithms, and more.

**Example 1: Uniform Distribution**

In [53]:
random_array = np.random.rand(3, 3)  # 3x3 matrix of random numbers
print(random_array)


[[0.25165855 0.98502919 0.51178389]
 [0.31131826 0.02912465 0.19642312]
 [0.23448057 0.64541882 0.06229112]]


**Explanation:** np.random.rand() generates random numbers uniformly distributed between 0 and 1.

**Example 2: Normal Distribution**

In [56]:
normal_array = np.random.randn(3, 3)  # 3x3 matrix of normally distributed numbers
print(normal_array)


[[ 0.20785436  0.29375132 -0.35294785]
 [-1.58776581 -0.0971634  -0.30921215]
 [-0.0539576   0.17184343 -1.14954557]]


**Explanation:** np.random.randn() generates random numbers from a standard normal distribution (mean 0, variance 1).

# 9. Assignments

**Basic Assignments**

1. Create a 1D Numpy array with 10 elements and access the 5th element.
2. Create a 3x3 identity matrix.
   
**Intermediate Assignments**

1. Given a 2D array, find the sum of all elements in each row.
2. Generate a 5x5 matrix with random numbers and calculate the mean and standard deviation.
   
# Advanced Assignments

Perform matrix multiplication on two 3x3 matrices and verify the result manually.


In [3]:
import numpy as np

In [5]:
#1 
 
arr=np.array([1,2,3,4,5,6,7,8,9,0])
arr[4]

5

In [22]:
#2
id=np.array([[1,0,0],[0,1,0],[0,0,1]])
print (id)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [12]:
#another way 
id1=np.identity(3,dtype=int)
print(id1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
#1
a=np.array([[1,2],[3,4]])
row_sum=np.sum(a,axis=1)
print(res)

[3 7]


In [32]:
#2
b=np.random.rand(5,5)
print(b)
print(b.mean())
print(b.std())

[[0.28914104 0.25869732 0.16099666 0.12275935 0.3216284 ]
 [0.95183281 0.52847876 0.98367625 0.38898196 0.41560866]
 [0.31448023 0.6381302  0.54748194 0.24018351 0.85878659]
 [0.92763903 0.50319962 0.84696319 0.8572616  0.50933801]
 [0.19708168 0.46945299 0.4464078  0.68621181 0.10403401]]
0.5027381356363831
0.2698080680344437


In [40]:
#Perform matrix multiplication on two 3x3 matrices and verify the result manually.
x=np.array([[1,0,0],[0,1,0],[0,0,1]])
y=np.array([[1,2,3],[2,1,3],[2,3,1]])
prod=np.dot(x,y)
print(prod)

[[1 2 3]
 [2 1 3]
 [2 3 1]]
